In [327]:
#Decision tree of OneAPI on Insurance Fraud Detection dataset

In [404]:
import daal4py as d4p
import numpy as np

import pandas 

In [405]:
read_csv = pandas.read_csv("[Dataset]_Module11_(Insurance).csv")

In [406]:
features = []
for col in read_csv.columns:
    if col != 'fraud_reported':
        features.append(col)

target = 'fraud_reported'

X = read_csv[features]
y = read_csv[target]

In [407]:
#Syntax: X_train, X_test, y_train, y_test = train_test_split()
from sklearn.model_selection import train_test_split
data, prunedata, labels, prunelabels = train_test_split(X, y, random_state = 1)

In [408]:
#Here,
#X_train = data
#y_train = labels
#X_test = prunedata
#y_test = prunelabels

In [409]:
train_algo = d4p.decision_tree_classification_training(2)

In [410]:
train_result = train_algo.compute(data, labels, prunedata, prunelabels)

In [411]:
predict_algo = d4p.decision_tree_classification_prediction()

predict_result = predict_algo.compute(prunedata, train_result.model)  #We pass X_test in predict_result (X_test = prunedata)

In [412]:
print("\nDecision tree prediction results (first 10 rows):\n", predict_result.prediction[0:10])
print("\nGround truth (first 10 rows):\n", prunelabels[0:10])


Decision tree prediction results (first 10 rows):
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]

Ground truth (first 10 rows):
 507    0
818    0
452    0
368    1
242    0
929    1
262    1
810    0
318    0
49     0
Name: fraud_reported, dtype: int64


In [413]:
from sklearn.metrics import confusion_matrix, classification_report

In [414]:
a = predict_result.prediction.reshape(-1) ##y_pred

In [415]:
b = prunelabels  #y_test

In [416]:
confusion_matrix(b,a)

array([[168,  12],
       [ 11,  59]], dtype=int64)

In [417]:
print(classification_report(b,a))

              precision    recall  f1-score   support

           0       0.94      0.93      0.94       180
           1       0.83      0.84      0.84        70

    accuracy                           0.91       250
   macro avg       0.88      0.89      0.89       250
weighted avg       0.91      0.91      0.91       250



In [403]:
#kNN of OneAPI on Insurance Fraud Detection dataset

In [440]:
import daal4py as d4p
import numpy as np
import pandas 

In [441]:
read_csv = pandas.read_csv("C:\\Users\\INDIA AI DATA LAB\\Downloads\\AIDA-Course\\AIDA-Course\\Module 11\\[Dataset]_Module11_(Insurance).csv")

In [442]:
features = []
for col in read_csv.columns:
    if col != 'fraud_reported':
        features.append(col)

target = 'fraud_reported'

X = read_csv[features]
y = read_csv[target]

In [443]:
#Syntax: X_train, X_test, y_train, y_test = train_test_split()
from sklearn.model_selection import train_test_split
data, prunedata, labels, prunelabels = train_test_split(X, y, random_state = 1)

In [444]:
nFeatures = 2
nClasses = 2

In [445]:
train_algo = d4p.kdtree_knn_classification_training(nClasses=nClasses)
#weights = np.ones((data.shape[0], 1))
train_result = train_algo.compute(data, labels)

In [446]:
predict_algo = d4p.kdtree_knn_classification_prediction(nClasses=nClasses)
predict_result = predict_algo.compute(prunedata, train_result.model)

In [447]:
print("kNN classification results:")
print("Ground truth(observations #13-14):\n", prunelabels[13:15])
print("Classification results(observations #13-14):\n", predict_result.prediction[13:15])

kNN classification results:
Ground truth(observations #13-14):
 345    0
971    0
Name: fraud_reported, dtype: int64
Classification results(observations #13-14):
 [[0.]
 [0.]]


In [448]:
from sklearn.metrics import confusion_matrix, classification_report
#a = predict_result.prediction.reshape(-1)
a = predict_result.prediction  #Here, result is same without reshape too, check how?
b = prunelabels

In [449]:
confusion_matrix(b,a)

array([[143,  37],
       [ 60,  10]], dtype=int64)

In [450]:
print(classification_report(b,a))

              precision    recall  f1-score   support

           0       0.70      0.79      0.75       180
           1       0.21      0.14      0.17        70

    accuracy                           0.61       250
   macro avg       0.46      0.47      0.46       250
weighted avg       0.57      0.61      0.59       250



In [451]:
#Decision forest of OneAPI on Insurance Fraud Detection dataset

In [355]:
import daal4py as d4p
import numpy as np

import pandas 

In [356]:
read_csv = pandas.read_csv("C:\\Users\\INDIA AI DATA LAB\\Downloads\\AIDA-Course\\AIDA-Course\\Module 11\\[Dataset]_Module11_(Insurance).csv")

In [357]:
features = []
for col in read_csv.columns:
    if col != 'fraud_reported':
        features.append(col)

target = 'fraud_reported'

X = read_csv[features]
y = read_csv[target]

In [358]:
#Syntax: X_train, X_test, y_train, y_test = train_test_split()
from sklearn.model_selection import train_test_split
data, prunedata, labels, prunelabels = train_test_split(X, y, random_state = 1)

In [359]:
# Lets configure a training object (5 classes)
train_algo = d4p.decision_forest_classification_training(5,
                                                         nTrees=10,
                                                         minObservationsInLeafNode=8,
                                                         featuresPerNode=3,
                                                         engine = d4p.engines_mt19937(seed=777),
                                                         varImportance='MDI',
                                                         bootstrap=True,
                                                         resultsToCompute='computeOutOfBagError')

In [360]:
train_result = train_algo.compute(data, labels)

In [361]:
predict_algo = d4p.decision_forest_classification_prediction(nClasses=5)
predict_result = predict_algo.compute(prunedata, train_result.model)
assert(predict_result.prediction.shape == (prunedata.shape[0], 1))
#We pass x_test(prunedata here) in predict_result 

In [362]:
#And then we compare y_pred(predict_result.prediction here) with y_test(prunelabels here)
print("\nRandom forest prediction results (first 10 rows):\n", predict_result.prediction[0:10])
print("\nGround truth (first 10 rows):\n", prunelabels[0:10])


Random forest prediction results (first 10 rows):
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Ground truth (first 10 rows):
 507    0
818    0
452    0
368    1
242    0
929    1
262    1
810    0
318    0
49     0
Name: fraud_reported, dtype: int64


In [363]:
from sklearn.metrics import confusion_matrix, classification_report
a = predict_result.prediction.reshape(-1)
b = prunelabels

In [364]:
confusion_matrix(b,a)

array([[178,   2],
       [ 59,  11]], dtype=int64)

In [365]:
print(classification_report(b,a))

              precision    recall  f1-score   support

           0       0.75      0.99      0.85       180
           1       0.85      0.16      0.27        70

    accuracy                           0.76       250
   macro avg       0.80      0.57      0.56       250
weighted avg       0.78      0.76      0.69       250



In [366]:
#SVM of OneAPI on Insurance fraud detection dataset 

In [367]:
import daal4py as d4p 
import numpy as np
import pandas 

In [368]:
read_csv = pandas.read_csv("C:\\Users\\INDIA AI DATA LAB\\Downloads\\AIDA-Course\\AIDA-Course\\Module 11\\[Dataset]_Module11_(Insurance).csv")

In [369]:
features = []
for i in read_csv.columns:
    if i != 'fraud_reported':
        features.append(i)

target = 'fraud_reported'
X = read_csv[features]
y = read_csv[target]    


In [370]:
y[y==0] = -1    #Changing all 0 values to 1 as svm can only distinguish bw -1 and 1 labels

In [371]:
y.value_counts()

fraud_reported
-1    753
 1    247
Name: count, dtype: int64

In [372]:
from sklearn.model_selection import train_test_split
data, prunedata, labels, prunelabels = train_test_split(X, y, random_state = 1)

In [373]:
train_algo = d4p.svm_training()

In [374]:
train_result = train_algo.compute(data, labels)

In [375]:
predict_algo = d4p.svm_prediction()

In [376]:
predict_result =predict_algo.compute(prunedata, train_result.model) 

In [377]:
#assert(predict_result.prediction.shape == (prunedata.shape[0], 1))

In [378]:
print("\nSupport Vector Machine prediction results (first 10 rows):\n", predict_result.prediction[0:10])
print("\nGround truth (first 10 rows):\n", prunelabels[0:10])


Support Vector Machine prediction results (first 10 rows):
 [[-1.30911009]
 [-1.21683948]
 [-1.96909834]
 [-1.12062208]
 [-2.13948189]
 [-0.48394354]
 [ 0.91034205]
 [-1.81697164]
 [-0.07427428]
 [ 0.50070007]]

Ground truth (first 10 rows):
 507   -1
818   -1
452   -1
368    1
242   -1
929    1
262    1
810   -1
318   -1
49    -1
Name: fraud_reported, dtype: int64


In [379]:
#SVM can only distinguish between -1 and 1 results thus we coverted our negative values to -1 and positive values to 1
a = predict_result.prediction.reshape(-1)
b =[ -1 if v<0 else 1 for v in a]
print(b)

[-1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, 1, -1, 1, 1, 1, -1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, -1, 1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, 1, -1, 1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, 1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, 1, 1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, -1, -1, -1, 1, -1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, -1]


In [380]:
print("\nSupport Vector Machine prediction results (first 10 rows):\n", b[0:10])  # b is y_pred(converted from predict_result.prediction)
print("\nGround truth (first 10 rows):\n", prunelabels[0:10])


Support Vector Machine prediction results (first 10 rows):
 [-1, -1, -1, -1, -1, -1, 1, -1, -1, 1]

Ground truth (first 10 rows):
 507   -1
818   -1
452   -1
368    1
242   -1
929    1
262    1
810   -1
318   -1
49    -1
Name: fraud_reported, dtype: int64


In [381]:
from sklearn.metrics import confusion_matrix, classification_report
#a = predict_result.prediction.reshape(-1) 
c = prunelabels 

In [382]:
#Here, c is y_test and b is y_pred(converted in -1 and 1)
confusion_matrix(b,c)

array([[140,  45],
       [ 40,  25]], dtype=int64)

In [383]:
print(classification_report(b,c))

              precision    recall  f1-score   support

          -1       0.78      0.76      0.77       185
           1       0.36      0.38      0.37        65

    accuracy                           0.66       250
   macro avg       0.57      0.57      0.57       250
weighted avg       0.67      0.66      0.66       250



In [384]:
#Multinomial Naive Bayes of OneAPI on Insurance fraud detection dataset 

In [452]:
import daal4py as d4p
import pandas 

In [453]:
read_csv = pandas.read_csv("C:\\Users\\INDIA AI DATA LAB\\Downloads\\AIDA-Course\\AIDA-Course\\Module 11\\[Dataset]_Module11_(Insurance).csv")

In [454]:
features = []
for col in read_csv.columns:
    if col != 'target_reported':
        features.append(col)
target = 'fraud_reported'
X = read_csv[features]
y = read_csv[target]

In [455]:
#Syntax: X_train, X_test, y_train, y_test = train_test_split()
from sklearn.model_selection import train_test_split
data, prunedata, labels, prunelabels = train_test_split(X,y, random_state=1)

In [456]:
train_algo = d4p.multinomial_naive_bayes_training(2)
train_result = train_algo.compute(data, labels)

In [457]:
predict_algo = d4p.multinomial_naive_bayes_prediction(2)
predict_result = predict_algo.compute(prunedata, train_result.model)

In [458]:
print("\nMultinomial Naive Bayes prediction results (first 10 rows):\n", predict_result.prediction[0:10])  
print("\nGround truth (first 10 rows):\n", prunelabels[0:10])


Multinomial Naive Bayes prediction results (first 10 rows):
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Ground truth (first 10 rows):
 507    0
818    0
452    0
368    1
242    0
929    1
262    1
810    0
318    0
49     0
Name: fraud_reported, dtype: int64


In [469]:
from sklearn.metrics import confusion_matrix, classification_report
a = predict_result.prediction #y_pred
b = prunelabels #y_test

In [470]:
confusion_matrix(b,a)

array([[180,   0],
       [ 70,   0]], dtype=int64)

In [471]:
print(classification_report(b,a))

              precision    recall  f1-score   support

           0       0.72      1.00      0.84       180
           1       0.00      0.00      0.00        70

    accuracy                           0.72       250
   macro avg       0.36      0.50      0.42       250
weighted avg       0.52      0.72      0.60       250



C:\Users\INDIA AI DATA LAB\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\INDIA AI DATA LAB\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\INDIA AI DATA LAB\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [ ]:
#Logistic Regression of OneAPI on Insurance fraud detection dataset

In [472]:
import daal4py as d4p
import pandas

In [474]:
read_csv = pandas.read_csv("C:\\Users\\INDIA AI DATA LAB\\Downloads\\AIDA-Course\\AIDA-Course\\Module 11\\[Dataset]_Module11_(Insurance).csv")

In [475]:
features = []
for col in read_csv:
    if col != 'fraud_reported':
        features.append(col)

target = 'fraud_reported'

X = read_csv[features]
y = read_csv[target]

In [476]:
from sklearn.model_selection import train_test_split
data, prunedata, labels, prunelabels = train_test_split(X, y, random_state = 1) 

In [481]:
train_algo = d4p.logistic_regression_training(2)
train_result = train_algo.compute(data,labels)

In [482]:
predict_algo = d4p.logistic_regression_prediction(2)
predict_result = predict_algo.compute(prunedata, train_result.model)

In [490]:
print("\nLogistic Regression prediction results (first 10 rows):\n", predict_result.prediction[0:10])  
print("\nGround truth (first 10 rows):\n", prunelabels[0:10])


Logistic Regression prediction results (first 10 rows):
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Ground truth (first 10 rows):
 507    0
818    0
452    0
368    1
242    0
929    1
262    1
810    0
318    0
49     0
Name: fraud_reported, dtype: int64


In [487]:
from sklearn.metrics import confusion_matrix, classification_report
a = predict_result.prediction #y_pred
b = prunelabels #y_test

In [488]:
confusion_matrix(b,a)

array([[167,  13],
       [ 67,   3]], dtype=int64)

In [489]:
print(classification_report(b,a))

              precision    recall  f1-score   support

           0       0.71      0.93      0.81       180
           1       0.19      0.04      0.07        70

    accuracy                           0.68       250
   macro avg       0.45      0.49      0.44       250
weighted avg       0.57      0.68      0.60       250



In [491]:
#Classification algorithms used here and their accuracy:
#1 Decision Tree = 91%
#2 K-nearest neighbour = 61%
#3 Decision Forest = 76%
#4 SVM = 66%
#5 Multinomial Naive Bayes = 72%
#6 Logistic Regression = 68%

In [ ]:
#Perform all classification algorithms on Recommendation system